name = "SimpleUI"
uuid = "7d5ddd29-585a-4ccb-ac42-b8c514ef29f6"
authors = ["GHTaarn <62629455+GHTaarn@users.noreply.github.com>"]
version = "0.2.0-DEV"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
julia = "1.5 - 1.11"
# Upwards restriction on Julia because TerminalMenus is not public,
# so the upper limit may be increased if `pick_file()` is tested
# and works on the given version.
